version: '3.9'
services:
  embedding-server:
    build:
      context: .
      dockerfile: embedding-server/Dockerfile.embedding
    ports:
      - "5000:5000"
    container_name: iguide-embedding-server

  metadata-extraction-server:
    build:
      context: .
      dockerfile: metadata-extraction-server/Dockerfile.metadata
    ports:
      - "5001:5001"
    container_name: iguide-metadata-server
